{
  "clean": false,
  "objc": false,
  "sdk": "iphone",
  "author": "Nexmo",
  "author_url": "https://nexmo.com",
  "github_url": "https://github.com/Nexmo/conversation-ios-sdk",
  "readme": "readme.md",
  "documentation": "./*.md",
  "output": "Docs",
  "exclude": "NexmoConversation/Private/ConversationClient+Private.swift",
  "module": "NexmoConversation",
  "custom_categories": [
    {
        "name": "Client",
        "children": [
            "ConversationClient",
            "SynchronizingState"
        ]
    },
    {
        "name": "Configuration",
        "children": [
            "Configuration"
        ]
    },
    {
        "name": "Facade",
        "children": [
            "Conversation",
            "Member",
            "ReceiptRecord",
            "User",
            "Audio"
        ]
    },
    {
        "name": "Controller",
        "children": [
            "AccountController",
            "ConversationController",
            "AppLifecycleController",
            "MediaController",
            "PushNotificationController",
            "RTCController"
        ]
    },
    {
        "name": "Event",
        "children": [
            "EventBase",
            "TextEvent",
            "ImageEvent",
            "MediaEvent",
            "MembershipEvent",
            "MemberLeftEvent",
            "MemberJoinedEvent",
            "MemberInvitedEvent"
        ]
    },
    {
        "name": "Model",
        "children": [
            "Event",
            "ConversationModel",
            "MemberModel",
            "NetworkError",
            "PushNotificationCertificate",
            "Session",
            "UploadedImage",
            "ConversationPreviewModel"
        ]
    },
    {
        "name": "Collection",
        "children": [
            "LazyCollection",
            "ConversationCollection",
            "MemberCollection",
            "ReceiptCollection",
            "EventCollection"
        ]
    },
    {
        "name": "Builder",
        "children": [
            "CreateConversation",
            "JoinConversation"
        ]
    }
  ]
}
