identifier_name: 
  min_length: 1
  max_length: 40
force_cast: error
force_try: error
force_unwrapping: error
implicitly_unwrapped_optional: error
function_body_length: 
  error: 300
cyclomatic_complexity:
  warning: 20
  error: 50
opt_in_rules:
- class_delegate_protocol
- closing_brace          
- closure_parameter_position
- colon                     
- comma                     
- compiler_protocol_init    
- control_statement         
- custom_rules              
- cyclomatic_complexity     
- discarded_notification_center_observer
- dynamic_inline                        
- empty_parameters                      
- empty_parentheses_with_trailing_closure
- file_length                            
- for_where                              
- force_cast                             
- force_try 
- force_unwrapping
- implicitly_unwrapped_optional
- function_body_length                   
- function_parameter_count               
- generic_type_name                      
- identifier_name                        
- implicit_getter                        
- large_tuple                            
- leading_whitespace                     
- legacy_cggeometry_functions            
- legacy_constant                        
- legacy_constructor                     
- legacy_nsgeometry_functions            
- line_length                                                            
- nesting                                
- notification_center_detachment         
- opening_brace                          
- operator_whitespace                    
- private_unit_test                      
- redundant_discardable_let              
- redundant_optional_initialization      
- redundant_string_enum_value            
- redundant_void_return                  
- return_arrow_whitespace                
- shorthand_operator                     
- statement_position                     
- syntactic_sugar                        
- todo                                   
- trailing_comma                         
- trailing_newline                       
- trailing_semicolon                     
- trailing_whitespace                    
- type_body_length                       
- type_name                              
- unused_closure_parameter               
- unused_enumerated                      
- unused_optional_binding                
- valid_ibinspectable                    
- vertical_parameter_alignment           
- vertical_whitespace                    
- void_return                            
- weak_delegate
disabled_rules:
- mark
- line_length
- operator_whitespace
- trailing_whitespace 
- function_parameter_count
- nesting 
- type_name       
excluded:
  - Carthage
  - Pods
  - Build
  - DerivedData
  - docs
  - Fastlane
  - mocket-io
  - ModuleCache
  - Scripts
  - ConversationDemo
  - ConversationDemoTests
  - ConversationDemoUITests